#!/bin/bash

CONFIG="$HOME/.config/waybar/config.jsonc"
STYLE="$HOME/.config/waybar/style.css"

CONFIG_FILES="$CONFIG $STYLE"

trap "killall waybar" EXIT

while true; do
    waybar 
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar


done